#+TITLE:      相关问题

* 目录                                                    :TOC_4_gh:noexport:
- [[#mysql-中-schema-和-database-的区别是什么][MySQL 中 Schema 和 Database 的区别是什么]]
- [[#时区陷阱问题][时区陷阱问题]]
- [[#怎样执行-sql-脚本][怎样执行 SQL 脚本]]
- [[#怎样通过远程主机进行访问][怎样通过远程主机进行访问]]
- [[#怎样在数据存在时更新不存在时插入][怎样在数据存在时更新不存在时插入]]
- [[#怎样显示-table-的元数据信息][怎样显示 Table 的元数据信息]]
- [[#countast-和-count1][COUNT(\ast) 和 COUNT(1)]]
- [[#怎样修改列值为允许为空][怎样修改列值为允许为空]]
- [[#语句-on-duplicate-key-update-的受影响行数][语句 ON DUPLICATE KEY UPDATE 的受影响行数]]
- [[#mysql-中的-select-和-group-by][MySQL 中的 SELECT 和 GROUP BY]]
- [[#mysql-中-update-语句影响行数为-0-的问题][MySQL 中 UPDATE 语句影响行数为 0 的问题]]
- [[#mysql-如何对死锁进行检测][MySQL 如何对死锁进行检测]]
- [[#mysql-中-varchar-类型到底能存多少汉字][MySQL 中 VARCHAR 类型到底能存多少汉字]]
- [[#join-using-和-join-on][JOIN USING 和 JOIN ON]]
- [[#mysql-中比较操作对于字符串尾空字符的处理][MySQL 中比较操作对于字符串尾空字符的处理]]

* MySQL 中 Schema 和 Database 的区别是什么
  MySQL 中 Schema 和 Database 在语义上是等价的，两者可以等价替换。

  参考：[[https://stackoverflow.com/questions/11618277/difference-between-schema-database-in-mysql][Difference Between Schema / Database in MySQL - Stack Overflow]]

* 时区陷阱问题
  ~mysql~ 6.0 以上的版本需要在链接字符串中假设参数 ~serverTimezone~ 指定时区：
  #+BEGIN_SRC xml
    <property name="url" value="jdbc:mysql://localhost:3306/springdatastudy?serverTimezone=UTC"/>
  #+END_SRC

  但是设置 ~UTC~ 时区可能导致时间精度的问题， 因此可以设置为中国标准时间：
  #+BEGIN_SRC xml
    <property name="url" value="jdbc:mysql://localhost:3306/springdatastudy?serverTimezone=Asia/Shanghai"/>
  #+END_SRC

* 怎样执行 SQL 脚本
  #+BEGIN_SRC bash
    mysql> source /path/to/script
  #+END_SRC

* 怎样通过远程主机进行访问
  + 更改配置文件中的 ~bind-address~ 为 ~0.0.0.0~, 配置文件在 ~/etc/mysql/~, 使得允许远程主机访问
  + 更改用户的 ~host~ 为 ~%~, 允许该用户进行远程访问
     #+BEGIN_SRC sql
       > use mysql;
       > UPDATE USER SET HOST='%' WHERE user='user_name';
     #+END_SRC     
  + 通过如下方式创建拥有所有权限可远程访问的用户
    #+BEGIN_SRC sql
      CREATE USER 'user'@'%' IDENTIFIED BY 'password';

      GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' = WITH GRANT OPTION;

      FLUSH PRIVILEGES;
    #+END_SRC

* 怎样在数据存在时更新不存在时插入
  #+BEGIN_SRC sql
    IF EXISTS(SELECT * FROM tbl WHERE id = 30122)
      UPDATE tbl SET name = 'john' WHERE id = 3012
    ELSE
      INSERT INTO tbl(name) VALUES('john');
  #+END_SRC

  如果存在键约束的话，也可以选择使用：
  #+begin_src sql
    INSERT ... ON DUPLICATE KEY UPDATE ...
  #+end_src

  参考：[[https://stackoverflow.com/questions/548541/insert-ignore-vs-insert-on-duplicate-key-update][mysql - "INSERT IGNORE" vs "INSERT ... ON DUPLICATE KEY UPDATE" - Stack Overflow]]

* 怎样显示 Table 的元数据信息
  通过 ~SHOW COLUMNS FROM tblName~ 可以显示表的元数据信息，但是也可以通过 ~DESCRIBE tblName~ 快速查询。

* COUNT(\ast) 和 COUNT(1)
  常见的一个需求就是通过 ~COUNT~ 函数来统计行数，其中一个问题就是 ~COUNT(\ast)~ 和 ~COUNT(1)~ 这两种写法的性能问题。

  这在 ~5.7~ 的文档中有相应的描述，对于 InnoDB 引擎来说，两种写法没有区别：
  #+begin_quote
  InnoDB handles SELECT COUNT(*) and SELECT COUNT(1) operations in the same way. There is no performance difference.
  #+end_quote

  对于 MyISAM 引擎来说，似乎 ~COUNT(*)~ 的写法会更好：
  #+begin_quote
  For MyISAM tables, COUNT(*) is optimized to return very quickly if the SELECT retrieves from one table, no other columns are retrieved, and there is no WHERE clause.

  This optimization only applies to MyISAM tables, because an exact row count is stored for this storage engine and can be accessed very quickly. COUNT(1) is only subject to the same optimization if the first column is defined as NOT NULL.
  #+end_quote

  官方文档链接：[[https://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html#function_count][MySQL :: MySQL 5.7 Reference Manual :: COUNT(expr)]]

  如果继续查阅文档，可以发现，即使在更早的版本 ~5.5~ 中，关于 COUNT 函数的描述也是一样的，因此，用 ~COUNT(*)~ 就可以了。

  但是，在实际的使用中，我们编写的 SQL 语句在到达数据库之前，可能会将 * 转换为列名，因此，在这种情况下，使用 ~COUNT(1)~ 更好。

* 怎样修改列值为允许为空
  #+begin_src sql
    ALTER TABLE mytable MODIFY mycolumn VARCHAR(255);
  #+end_src

  参考：
  + [[https://stackoverflow.com/questions/212939/how-do-i-modify-a-mysql-column-to-allow-null][syntax - How do I modify a MySQL column to allow NULL? - Stack Overflow]]

* 语句 ON DUPLICATE KEY UPDATE 的受影响行数
  #+begin_quote
  With ON DUPLICATE KEY UPDATE, the affected-rows value per row is 1 if the row is inserted as a new row and 2 if an existing row is updated.
  #+end_quote

  参考：
  + [[https://stackoverflow.com/questions/3747314/why-are-2-rows-affected-in-my-insert-on-duplicate-key-update][mysql - Why are 2 rows affected in my `INSERT ... ON DUPLICATE KEY UPDATE`? - Stack Overflow]]

* MySQL 中的 SELECT 和 GROUP BY
  在 SQL Server 中，SELECT 只能查询在 GROUP BY 子句中出现的字段，但是在 MySQL 中，如果 SELECT 中存在不在 GROUP BY 子句中的字段，
  就会任意选择一行数据数据。

  每次用 MySQL 都以为我记错了 QAQ

  参考：
  #+begin_quote
  A MySQL extension permits a column that does not appear in the GROUP BY list to be named in the select list. (For information about nonaggregated columns and GROUP BY, see Section 12.20.3, “MySQL Handling of GROUP BY”.)
  In this case, the server is free to choose any value from this nonaggregated column in summary rows, and this includes the extra rows added by WITH ROLLUP. 
  #+end_quote

  [[https://dev.mysql.com/doc/refman/8.0/en/group-by-modifiers.html][MySQL :: MySQL 8.0 Reference Manual :: 12.20.2 GROUP BY Modifiers]]

* MySQL 中 UPDATE 语句影响行数为 0 的问题
  MySQL 在官方文档中的描述：
  #+begin_quote
  If you set a column to the value it currently has, MySQL notices this and does not update it.
  #+end_quote

  也就是说，当要更新的值和原始值一样时，MySQL 就不会执行更新，当所有值都一样时，就不会进行修改，影响行数自然为 0。

  参考：
  + [[https://stackoverflow.com/questions/2186887/mysql-update-query-returns-0-rows-affected][mySQL UPDATE query returns "0 rows affected" - Stack Overflow]]

* MySQL 如何对死锁进行检测
  有两种方式：
  1. 当事务等待时间超过一定时间时就认为存在死锁，这时会选择回滚等待的事务中的一个或多个
  2. 通过 wait-for graph 算法进行检测，当存在环路时就认为出现了死锁

  参考：
  + [[https://www.cnblogs.com/lbser/p/5183300.html][mysql 死锁问题分析 - zhanlijun - 博客园]]

* MySQL 中 VARCHAR 类型到底能存多少汉字
  + mysql 4.0 版本以下，varchar(50)，指的是 50 字节，如果存放 utf8 汉字时，只能存放 16 个（每个汉字 3 字节）
  + mysql 5.0 版本以上，varchar(50), 指的是 50 字符，无论存放的是数字、字母还是 UTF8 汉字，都可以存放 50 个

* JOIN USING 和 JOIN ON
  USING 某种程度上来说算是一个语法糖，一些比较好的地方：
  1. 当连接的两张表存在相同字段时，使用 USING 更加方便：
     #+begin_src sql
       -- using
       SELECT film.title, film_id -- film_id is not prefixed
       FROM film
       JOIN film_actor USING (film_id)
       WHERE ...

       -- on
       SELECT film.title, film.film_id -- film.film_id is required here
       FROM film
       JOIN film_actor ON (film.film_id = film_actor.film_id)
       WHERE ...
     #+end_src
  2. =SELECT *= 时 ON 会返回相同字段两次，而 USING 只返回一次

  参考：
  + [[https://stackoverflow.com/questions/11366006/mysql-on-vs-using][join - MySQL ON vs USING? - Stack Overflow]]

* MySQL 中比较操作对于字符串尾空字符的处理
  在测试环境中遇到的问题，执行类似如下的 SQL 时得到了 TRUE 结果：
  #+begin_src sql
    SELECT 'string' = 'string   '
  #+end_src

  当场觉得 SQL 白学了，官方对此的文档是这样的([[https://dev.mysql.com/doc/refman/8.0/en/charset-binary-collations.html#charset-binary-collations-trailing-space-comparisons][link]])：
  #+begin_quote
  MySQL collations have a pad attribute, which has a value of PAD SPACE or NO PAD:
  + Most MySQL collations have a pad attribute of PAD SPACE.
  + The Unicode collations based on UCA 9.0.0 and higher have a pad attribute of NO PAD; see Section 10.10.1, “Unicode Character Sets”.

  For nonbinary strings (CHAR, VARCHAR, and TEXT values), the string collation pad attribute determines treatment in comparisons of trailing spaces at the end of strings:
  + For PAD SPACE collations, trailing spaces are insignificant in comparisons; strings are compared without regard to trailing spaces.
  + NO PAD collations treat trailing spaces as significant in comparisons, like any other character.
  #+end_quote

  简单来说，对于大多数的编码方式来说，字符串的 = 比较是不会比较尾空串的……

  可以通过 binary 关键字避免这一行为：
  #+begin_src sql
    SELECT BINARY 'string' = 'string   '
  #+end_src

