#+TITLE:      Linux 问题集

* 目录                                                    :TOC_4_gh:noexport:
- [[#如何快速删除文件][如何快速删除文件]]
- [[#避免-ssh-连接因超时闲置断开][避免 SSH 连接因超时闲置断开]]
  - [[#方案一客户端设置][方案一：客户端设置]]
  - [[#方案二在服务器端设置][方案二：在服务器端设置]]
- [[#忘记-root-密码怎么办][忘记 root 密码怎么办]]
- [[#如何强制用户下线][如何强制用户下线]]
- [[#怎样编译开源程序][怎样编译开源程序]]
- [[#怎样创建交换分区][怎样创建交换分区]]
- [[#怎样搭建-ftp-服务器][怎样搭建 FTP 服务器]]
- [[#怎样合并两个目录][怎样合并两个目录]]
- [[#怎样创建需要定时执行的任务][怎样创建需要定时执行的任务]]
- [[#x11gtkgnome-等之间的关系][X11、GTK、GNOME 等之间的关系]]
- [[#怎样关闭一个占用了指定端口的进程][怎样关闭一个占用了指定端口的进程]]
- [[#如何通过-shell-脚本分发软件包][如何通过 Shell 脚本分发软件包]]
- [[#在命令行生成文本-hash-摘要时得到的值不正确][在命令行生成文本 Hash 摘要时得到的值不正确]]

* 如何快速删除文件
  + [[https://www.slashroot.in/which-is-the-fastest-method-to-delete-files-in-linux][Which is the fastest method to delete files in Linux]]

  #+BEGIN_EXAMPLE
    $ perl -e 'for(<*>){((stat)[9]<(unlink))}'
  #+END_EXAMPLE

* 避免 SSH 连接因超时闲置断开
** 方案一：客户端设置
   编辑文件 ~/etc/ssh/ssh_config~, 添加如下一行：
   #+BEGIN_EXAMPLE
     ServerAliveInterval 60
   #+END_EXAMPLE

   *NOTE:* 是 ~ssh_config~ 不是 ~sshd_config~.

** 方案二：在服务器端设置
   编辑文件 ~/etc/ssh/sshd_config~ 并添加：
   #+BEGIN_EXAMPLE
     ClientAliveInterval 60
   #+END_EXAMPLE

   重启 SSH 服务后该项设置会生效，这样设置安全性会有一定下降。

* 忘记 root 密码怎么办
  1. 系统启动时按任意键进入如下界面：
     #+BEGIN_EXAMPLE
       root (hd0,0) 
       kernel /vmlinuz-2.6.18-128.el5 ro root=LABEL=/ rhgb quiet 
       initrd /initrd-2.6.18-128.el5.img 
     #+END_EXAMPLE

  2. 将光标移动到 kernel 那一行，按 e 进行编辑，在最后键入 ~single~:
     #+BEGIN_EXAMPLE
       kernel /vmlinuz-2.6.18-128.el5 ro root=LABEL=/ rhgb quiet single 
     #+END_EXAMPLE

  3. 按下 Enter 确定，按 b 进入单人维护模式。然后使用命令 ~passwd~ 修改密码

* 如何强制用户下线
  1. 命令 who 查看哪些用户在线
  2. 使用 ~pkill -kill -t pts/n~ 踢出用户

* 怎样编译开源程序
  通常的步骤：
  #+BEGIN_EXAMPLE
    ./configure - 生成 Makefile
    make - 编译
    make intsall - 安装
  #+END_EXAMPLE

  在第一步前也可能存在 ~./autogen.sh~ 这一步骤。
  
* 怎样创建交换分区
  #+BEGIN_SRC bash
    $ dd if=/dev/zero of=/root/.swap bs=1M count=128
    $ chmod 0600 /root/.swap
    $ mkswap /root/.swap
    $ swapon /root/.swap
    $ vim /etc/fstab
    # /root/.swap swap swap defaults 0 0
  #+END_SRC

* 怎样搭建 FTP 服务器
  教程：[[https://www.digitalocean.com/community/tutorials/how-to-set-up-vsftpd-for-a-user-s-directory-on-ubuntu-18-04][How To Set Up vsftpd for a User's Directory on Ubuntu 18.04 | DigitalOcean]]

  问题：
  1. 由于是云服务器，防火墙就不用管了，但是要添加安全组，开放 21 端口
  2. 用户的添加，Debian 需要使用 adduser 命令：[[https://askubuntu.com/questions/374870/home-directory-not-being-created][command line - Home directory not being created - Ask Ubuntu]]
  3. 服务器的配置跟着配就可以了，但是还有一个地方要改：[[https://askubuntu.com/questions/413677/vsftpd-530-login-incorrect][server - vsftpd: 530 Login incorrect - Ask Ubuntu]]
  4. 被动模式的配置：
     + [[https://www.cnblogs.com/kuliuheng/p/3209744.html][vsftpd的主动模式与被动模式 - VictoKu - 博客园]]
     + Debian 系统中 iptables 默认开发所有端口，不需要配置了
     + 服务器的安全组需要配置，开放需要的端口，例如 TCP:10240-20480
     + FTP 服务器网页可以查看文件，在资源管理器中打开可以上传文件
     + 链接格式： ftp://user:passwd@host

* 怎样合并两个目录
  方式一：通过 cp 命令合并目录：
  #+BEGIN_SRC bash
    $ cp -RT src dst
  #+END_SRC

  参考：[[https://stackoverflow.com/questions/4572225/how-do-i-merge-one-directory-into-another-using-bash][shell - How do I merge one directory into another using Bash? - Stack Overflow]]

  方式二：通过 rsync 命令合并目录：
  #+BEGIN_SRC bash
    rsync -a src/ dst/
  #+END_SRC

  参考：[[https://unix.stackexchange.com/questions/149965/how-to-copy-merge-two-directories][ubuntu - How to copy-merge two directories? - Unix & Linux Stack Exchange]]

* 怎样创建需要定时执行的任务
  通过 crontab 命令，我们可以在固定的间隔时间执行指定的系统指令或 shell script 脚本。

  参考：
  + [[https://linuxtools-rst.readthedocs.io/zh_CN/latest/tool/crontab.html][19. crontab 定时任务 — Linux Tools Quick Tutorial]]

* X11、GTK、GNOME 等之间的关系
  X11 是 X Window System Protocol, Version 11（RFC1013），是 X server 和 X client 之间的通信协议。X server 是 xfree86/xorg 驱动下的显示设备鼠标键盘统称，
  X client 通过 X11 协议和 xfree86/xorg 实现的 X server通信。

  为了方便开发人员编写 X clients，就有了 Xlib 来封装协议。Xlib 不够方便，于是就有了 QT 和 GTK，提供了很多窗口控件（widgets）。

  为了方便用户，就出现了 GNOME 和 KDE 等桌面管理系统。GNOME 用的是 GTK 库，KDE 用的是 QT 库。

  参考：
  + [[https://blog.csdn.net/chenglian_999/article/details/4927459][X11,GTK,QT,GNOME 的区别与联系 - chenglian_999的专栏 - CSDN博客]]
  + [[https://zh.wikipedia.org/wiki/X_Window%E7%B3%BB%E7%B5%B1][X 窗口系统 - 维基百科，自由的百科全书]]

* 怎样关闭一个占用了指定端口的进程
  简易版本为：
  #+begin_example
    kill -9 $(lsof -t -i tcp:8080)
  #+end_example

  更加完美的版本：
  #+begin_example
    kill -9 $(lsof -t -i:3000 -sTCP:LISTEN)
  #+end_example

  参考：
  + [[https://stackoverflow.com/questions/11583562/how-to-kill-a-process-running-on-particular-port-in-linux][unix - How to kill a process running on particular port in Linux? - Stack Overflow]]

* 如何通过 Shell 脚本分发软件包
  经常可以看到的一种分发包，就只是一个 Shell 脚本，内部同时包含了 Shell 脚本和二进制数据。

  这样做是因为 Bash 对于脚本中的二进制数据会选择忽略，因此，通过这种方式将脚本和二进制数据组合在一起的方式，使得安装的同时可以进行一些其他的操作。 

  参考：
  + [[https://unix.stackexchange.com/questions/27285/is-it-a-script-or-is-it-a-binary][linux - Is it a script or is it a binary? - Unix & Linux Stack Exchange]]
  + [[https://linux.cn/article-6291-1.html][技术|如何用 Bash 创建一个二进制发布包]]

* 在命令行生成文本 Hash 摘要时得到的值不正确
  有时会通过如下的方式来生成 Hash 摘要，但是会得到错误的值：
  #+begin_src bash
    $ echo foobar | sha256sum
  #+end_src
  
  这是因为 echo 通常会输出一个换行符，可以通过 ~-n~ 选项关闭这一行为：
  #+begin_src bash
    $ echo -n foobar | sha256sum
  #+end_src

