#+TITLE:      Emacs

* 目录                                                    :TOC_4_gh:noexport:
- [[#important-general-concepts][Important General Concepts]]
  - [[#screen][Screen]]
  - [[#user-input][User Input]]
  - [[#keys][Keys]]
  - [[#enter--exit][Enter & Exit]]
- [[#fundamental-editing-commands][Fundamental Editing Commands]]

* Important General Concepts
** Screen
   也许是 Emacs 的诞生比较早的原因，操作系统层面的单个窗口或终端界面在 Emacs 中的名称为 Frame。
  
   在 =Frame= 内部的才是 Emacs 的 Window，每个 Window 的最后一行是一个 mode line，整体结构为：
   #+begin_example
     Frame
       Menu bar
       Tool bar
       Window
         buffer text
         scroll bar
         mode line
       Echo area
   #+end_example  

   其中，echo area 还被用来显示 minibuffer（一个特殊的 Window），可以用个快捷键 =C-g= 退出 minibuffer。

** User Input
   Emacs 中可以将用户输入分为：
   + Simple characters 简单字符，包括字母、数字、符号和空格
   + Control characters 控制字符，包括 <RET>、<TAB>、<DEL>、<ESC>、<F1>、<HOME> 和 <LEFT> 等
   + Modifier keys，通过 <Control> 和 <Meta> 可以改变接下来输入的字符的含义，变为控制字符
     
   可以使用 <ESC> 来代替 <Meta> 键，而且 <ESC> 按下后可以松开，但是 <Meta> 不行，但是 <Meta> 近一点。

** Keys
   在 Emacs 中，一个按键序列 key sequnce，如 C-x C-f，或者一个短按键，如 C-f，被称作 =compile key=.

   对于 =C-x C-f= 这样的按键序列中，C-x 部分被称作 =prefix key=.

   Emacs 中默认的前缀键有：‘C-c’, ‘C-h’, ‘C-x’, ‘C-x <RET>’, ‘C-x @’, ‘C-x a’, ‘C-x n’, ‘C-x r’, ‘C-x v’, ‘C-x 4’, ‘C-x 5’, ‘C-x 6’, <ESC>, ‘M-g’, and ‘M-o’.
   (<F1> and <F2> are aliases for ‘C-h’ and ‘C-x 6’.)

   按键到具体命令之间的映射被叫做 ‘keymaps’。

** Enter & Exit
   在 Unix/Linux 系统中，通过命令行启动 Emacs 时可以使用 =&= 后缀避免阻塞终端界面。

   可以通过变量 =confirm-kill-emacs= 和 =confirm-kill-processes= 来控制关闭 Emacs 时的行为。

* Fundamental Editing Commands
  
