#+TITLE:      Emacs - 问题集

* 目录                                                    :TOC_4_gh:noexport:
- [[#怎样在-org-mode-的表格中插入竖线][怎样在 org-mode 的表格中插入竖线]]
- [[#怎样调整-python-代码块的缩进][怎样调整 Python 代码块的缩进]]
- [[#怎样设置某个-major-mode-的快捷键][怎样设置某个 Major mode 的快捷键]]
- [[#怎样获取光标位置的字体颜色][怎样获取光标位置的字体、颜色......]]
- [[#中英等宽字体的配置][中英等宽字体的配置]]
- [[#怎样选取-web-mode-的模板引擎][怎样选取 web-mode 的模板引擎]]
- [[#spacemacs-中那种-m-x-的命令列表怎么实现][Spacemacs 中那种 M-x 的命令列表怎么实现]]
- [[#怎样对齐-org-mode-中的标签][怎样对齐 Org-mode 中的标签]]
- [[#怎样在某个模式下禁用全局的-minor-mode][怎样在某个模式下禁用全局的 minor-mode]]
- [[#怎样通过-use-package-加载使用主题][怎样通过 use-package 加载使用主题]]
- [[#spacemacs-中进行粘贴时怎样保留内容缩进格式][Spacemacs 中进行粘贴时怎样保留内容缩进格式]]
- [[#怎样判断当前的环境是不是终端环境][怎样判断当前的环境是不是终端环境]]
- [[#如何自定义快捷键][如何自定义快捷键]]

* 怎样在 org-mode 的表格中插入竖线
  使用符号 ~\vert~ 代替，导出时会显示为竖线，参考：
  + [[https://orgmode.org/manual/Special-symbols.html][The Org Manual: Special symbols]]

* 怎样调整 Python 代码块的缩进
  选中代码然后通过快捷键 C-c < 或 C-c > 调整它们的缩进层次，参考：
  + [[https://stackoverflow.com/questions/2585091/emacs-bulk-indent-for-python][Emacs bulk indent for Python - Stack Overflow]]

* 怎样设置某个 Major mode 的快捷键
  #+BEGIN_SRC elisp
    (define-key name-mode-map (kbd "o") 'function)
  #+END_SRC

  参考：[[http://ergoemacs.org/emacs/emacs_set_keys_for_major_mode.html][Emacs: Change Major Mode Keys]]

* 怎样获取光标位置的字体、颜色......
  通过快捷键 C-u C-x = 获取光标所在位置的 face，face 会决定内容的显示模式。

  可以参考：[[http://ergoemacs.org/emacs/elisp_define_face.html][Elisp: How to Define Face]]

* 中英等宽字体的配置
  通过 cnfonts 可以快速的配置，也可以借鉴 Spacemacs 的配置：
  #+BEGIN_SRC elisp
    (defun spacemacs//set-monospaced-font (english chinese english-size chinese-size)
      "Set the monospaced font size when mixed Chinese and English words."
      (set-face-attribute 'default nil :font
                          (format   "%s:pixelsize=%d"  english english-size))
      (dolist (charset '(kana han cjk-misc bopomofo))
        (set-fontset-font (frame-parameter nil 'font) charset
                          (font-spec :family chinese :size chinese-size))))
  #+END_SRC

* 怎样选取 web-mode 的模板引擎
  通过调用函数 ~web-mode-set-engine~ 可以直接设置模板引擎，参考：
  + [[https://emacs.stackexchange.com/questions/23810/getting-proper-indentation-for-python-flask-templates][Getting proper indentation for Python Flask templates - Emacs Stack Exchange]]

* Spacemacs 中那种 M-x 的命令列表怎么实现
  可以通过 Ido、Helm 和 Ivy 来实现，可以参考如下链接中的内容：
  + [[https://github.com/lujun9972/emacs-document/blob/master/emacs-common/%E4%BB%8EHelm%E5%88%B0Ivy.org][从 Helm 到 Ivy]]
  + [[https://www.emacswiki.org/emacs/InteractivelyDoThings][EmacsWiki: Interactively Do Things]]
  + [[https://oremacs.com/swiper/#getting-started][Ivy User Manual]]

  根据字符串调用函数：
  #+BEGIN_SRC elisp
    (lambda (x) (command-execute (intern x)))
  #+END_SRC

* 怎样对齐 Org-mode 中的标签
  通过快捷键 C-u C-c C-q 就可以了
* 怎样在某个模式下禁用全局的 minor-mode
  #+BEGIN_SRC elisp
    (add-hook 'major-mode-hook (lambda () (minor-mode -1)))
  #+END_SRC

* 怎样通过 use-package 加载使用主题
  #+BEGIN_SRC elisp
    (use-package theme
      :ensure t
      :config (load-theme 'theme t))
  #+END_SRC

* Spacemacs 中进行粘贴时怎样保留内容缩进格式
  C-y	Automatically indenting after pasting. With prefix argument, paste text as it is.

* 怎样判断当前的环境是不是终端环境
  可以通过函数 ~display-graphic-p~ 进行判断，在配置主题这些东西的时候是一个很好用的功能：
  #+begin_src elisp
    (if (display-graphic-p) 
        (enable-theme 'solarized) 
      (enable-theme 'wheatgrass))
  #+end_src

  参考：
  + [[https://emacs.stackexchange.com/questions/13050/different-theme-for-nw-terminal][Different theme for -nw (terminal) - Emacs Stack Exchange]]

* 如何自定义快捷键
  通过函数 ~global-set-key~ 来设置全局的快捷键：
  #+BEGIN_SRC elisp
    (global-set-key (kbd "C-x C-\\") 'next-line)
    (global-set-key "\C-x\C-\\" 'next-line)
  #+END_SRC

  如果 ~C-x~ 已经是快捷键节，就需要先通过函数 ~global-unset-key~ 取消设置：
  #+BEGIN_SRC elisp
    (global-unset-key "\C-x")
  #+END_SRC

  通过 ~local-set-key~ 和 ~local-unset-key~ 设置指定模式下的快捷键。

  缓冲区本地快捷键可以参考： [[https://www.emacswiki.org/emacs/BufferLocalKeys][EmacsWiki: Buffer Local Keys]]

