#+TITLE:      Git - Github

* 目录                                                    :TOC_4_gh:noexport:
- [[#github-搜索][Github 搜索]]
- [[#问题集][问题集]]
  - [[#怎样同步-fork-的上游存储库][怎样同步 fork 的上游存储库]]
  - [[#怎样创建镜像存储库][怎样创建镜像存储库]]
  - [[#怎样解决访问慢的问题][怎样解决访问慢的问题]]
- [[#footnotes][Footnotes]]

* Github 搜索
  Github 提供了非常强大的搜索功能，让我们可以对 repositories、topics、code、commits、issues、pull requests、users、forks 等进行搜索。

  默认情况下，Github 使用的搜索方式是全文搜索[fn:1]，在需要时，我们还可以通过额外的语法对搜索结果进行限制，从而得到更为精确的搜索结果。

  比如说，现阶段对于我来说比较重要的需求是对 repositories 的搜索，而 Github 提供了很多相关的搜索限定符来辅助查询：
  + 通过 ~in~ 限定符指定搜索范围，默认为存储库的名称和描述
  + 通过 ~repo~ 限定符搜索指定的存储库
  + 通过 ~user~ 和 ~org~ 限定符指定用户和组织机构
  + 通过 ~size~ 限定符指定存储库的大小，单位是千字节
  + 通过 ~followers~ 限定符指定关注者数量
  + 通过 ~forks~ 限定符指定 fork 的数量
  + 通过 ~stars~ 限定符指定 star 的数量
  + 通过 ~created~ 和 ~pushed~ 限定符指定创建和推送时间
  + 通过 ~language~ 限定符指定语言
  + 通过 ~topic~ 限定符指定 topic
  + 通过 ~topics~ 限定符指定 topic 的数量
  + 通过 ~license~ 限定符指定存储库使用的 License
  + 通过 ~is:public~ 和 ~is:private~ 指定存储库的类型
  + 通过 ~mirror:boolean~ 指定存储库是否是镜像
  + 通过 ~archived:boolean~ 指定存储库是否归档    
  + 更多的内容可以参考：[[https://help.github.com/en/articles/searching-for-repositories][Searching for repositories - GitHub Help]]

  而 Github 还提供了更多的搜索功能，可以参考：[[https://help.github.com/en/categories/searching-for-information-on-github][Searching for information on GitHub - GitHub Help]]
  
  至于搜索语法的问题，可以说，很有 [[https://lucene.apache.org/core/2_9_4/queryparsersyntax.html][Apache Lucene - Query Parser Syntax]] 的既视感，不知道 Github 搜索用的是不是 ES。

* 问题集
** 怎样同步 fork 的上游存储库
   #+BEGIN_EXAMPLE
     $ git remote add upstream <remote-url>
     $ git fetch upstream
     $ git merge upstream/<branch>
   #+END_EXAMPLE

** 怎样创建镜像存储库
   #+begin_example
     $ git clone --bare https://github.com/exampleuser/old-repository.git
     $ cd old-repository.git
     $ git push --mirror https://github.com/exampleuser/new-repository.git
     $ cd ..
     $ rm -rf old-repository.git
   #+end_example

   参考：[[https://help.github.com/en/articles/duplicating-a-repository][Duplicating a repository - GitHub Help]]

** 怎样解决访问慢的问题
   其实 git clone 或者 git push 特别慢，并不是因为 http://github.com 的这个域名被限制了。而是 http://github.global.ssl.fastly.Net 这个域名被限制了。
   那么首先查到这个域名的 ip，然后在 hosts 文件中进行 ip -> 域名 映射就可以了。

   然而，考虑到 github 的 ip 地址会变的这个问题，这种方案不是很持久啊……

   参考：[[https://github.com/ly2011/blog/issues/126][完美解决 github 访问速度慢 · Issue #126 · ly2011/blog]]

* Footnotes

[fn:1] 计算机索引程序通过扫描文章中的每一个词，对每一个词建立一个索引，指明该词在文章中出现的次数和位置，当用户查询时，检索程序就根据事先建立的索引进行查找，并将查找的结果反馈给用户的检索方式 
