* 非递归的预测分析
  非递归的预测分析显示的维护一个栈，栈顶保存一个非终结符或终结符：
  1. 当栈顶为非终结符 X 时，根据输入符号 a 和预测分析表选择一个 X 的产生式
  2. 当栈顶为终结符 X 时，判断 X 和 a 是否匹配

  *非递归预测分析中的错误处理*

  同步词法单元的构造：
  1. 非终结符号 A 的 FOLLOW 集
  2. 如果非终结符可以推导出空串，就把可以推导出空串的产生式当做默认值使用

  错误处理：
  1. 如果 M[A, a] 为空，则输入符号 a 被忽略
  2. 如果该条目为同步词法单元，弹出栈顶非终结符
  3. 如果栈顶的 *词法单元* 和输入符号不匹配，那么弹出栈顶词法单元

* 自底向上的语法分析
  自底向上语法分析是一个 *最右推导* 的逆过程，常用技术为 *移入-规约* 语法分析技术。

  移入-规约语法分析器可能采取的动作：
  + *移入* - 将下一个输入符号移到栈的顶端
  + *规约* - 被规约的符号串的 *右端* 必然是 *栈顶*, 语法分析器在栈中确定这个串的 *左端*,
    并决定使用哪个非终结符来 *替换* 这个串
  + *接受* - 宣布语法分析过程成功完成
  + *报错* - 发现一个语法错误，并调用一个错误恢复子例程

** 项和 LR(0) 自动机
   对于产生式 ~A -> XYZ~ 来说，存在四个项：
   #+BEGIN_EXAMPLE
      A -> ·XYZ
      A -> X·YZ
      A -> XY·Z
      A -> XYZ·
   #+END_EXAMPLE

   对于移入-规约操作来说： ~A -> XYZ·~ 进行规约操作，其他进行移入操作。

   + *增广文法*

     如果文法 G 是一个以 S 为开始符号的文法，那么 G 的增广文法 G' 就是在 G 中假如新的开始符号 S'
     和产生式 S' -> S 得到的文法。

   + *项集的闭包*

     如果 *I* 是文法 *G* 的一个项集，那么 /CLOSURE(I)/ 可以根据以下两个规则得出：
     1. 一开始，将 *I* 中的各个项加入到 /CLOSURE(I)/ 中
     2. 如果 /CLOSURE(I)/  中存在点在 *·* 非终结符后，并且该非终结符的第一个项不在 /CLOSURE(I)/ 中，那么
        将该项添加到 /CLOSURE(I)/ 中。

     比如：
     #+BEGIN_EXAMPLE
       项集 I:

       E' -> ·E

       CLOSURE(I):

       E' -> ·E
       E -> ·E + T
       E -> ·T
       T -> ·T * F
       T -> ·F
       F -> ·(E)
       F -> ·id
     #+END_EXAMPLE

   + *GOTO 函数*

     GOTO(I, X)，其中 I 是一个项集而 X 是一个文法符号。GOTO(I, X) 被定义为 I 中所有形如
     [A -> a·XB] 的项所对应的的项 [A -> aX·B] 的集合的闭包。

