#+TITLE:      Java 问题集

* 目录                                                    :TOC_4_gh:noexport:
- [[#怎样执行包中的类][怎样执行包中的类]]
- [[#jdk--jre--jvm-各自的含义是什么][JDK & JRE & JVM 各自的含义是什么]]
- [[#java-的版本号是怎么回事][Java 的版本号是怎么回事]]
- [[#java-常用的构建工具有哪些][Java 常用的构建工具有哪些]]
- [[#java-程序的文件名有什么限制][Java 程序的文件名有什么限制]]
- [[#java-环境变量的配置问题][Java 环境变量的配置问题]]
- [[#java-资源问题][Java 资源问题]]
- [[#内部类引用外部类的实例][内部类引用外部类的实例]]
- [[#java-编程中-bean-类的含义][Java 编程中 Bean 类的含义]]
- [[#null-重载的问题][null 重载的问题]]
- [[#void-和-void-的使用][Void 和 void 的使用]]
- [[#怎样实现静态方法的链式调用][怎样实现静态方法的链式调用]]
- [[#parsexxx-和-valueof-的区别][parseXXX 和 valueOf 的区别]]
- [[#带标签的-break-与-continue-的使用][带标签的 break 与 continue 的使用]]
- [[#同名标识符的优先级][同名标识符的优先级]]
- [[#数组长度允许为-0-的好处][数组长度允许为 0 的好处]]

* 怎样执行包中的类
  #+BEGIN_EXAMPLE
    $ java package.class
  #+END_EXAMPLE

* JDK & JRE & JVM 各自的含义是什么
  Java SE - Java Platform, Standard Edition. Including JRE and JDK.

  + JVM(Java Virtual Machine), Java 虚拟机的缩写.
  + JRE(Java Runtime Environment), Java 运行环境的缩写. 运行 JAVA 程序所必须的环境的集合，
    包括 Java 虚拟机和 Java 程序所需的核心类库等， 如果想要运行一个开发好的 Java 程序，计算机中只需要安装 JRE 即可。
  + JDK(Java Development Kit), Java 开发工具包的缩写. JDK是提供给 Java 开发人员使用的，其中包含了 java 的开发工具，
    也包括了 JRE。所以安装了 JDK，就不用在单独安装 JRE 了。其中的开发工具： 编译工具(javac.exe)  打包工具(jar.exe)等。
  
  参考： [[https://blog.csdn.net/z15732621736/article/details/50603819][JDK、JRE、JVM 简介]]

* Java 的版本号是怎么回事
  |-------------+---------------|
  | Java 版本号 | JDK 版本号    |
  |-------------+---------------|
  | Java        | 1.02 - 1.4    |
  | Java2       | 1.2, 1.3, 1.4 |
  | Java5       | 1.5+          |
  |-------------+---------------|

* Java 常用的构建工具有哪些
  1. Gradle, Android 默认
  2. Maven, 使用者仍然很多
  3. Ant, 要凉

* Java 程序的文件名有什么限制
  + Java 保存的文件名必须与类名一致
  + 如果文件中只有一个类，文件名必须与类名一致
  + 一个 Java 文件中只能有一个 public 类
  + 如果文件中不止一个类，文件名必须与 public 类名一致
  + 如果文件中不止一个类，而且没有 public 类，文件名可与任一类名一致

  参考： [[https://blog.csdn.net/shaoxiaoning/article/details/40424087][Java 的类名与文件名必须一致]]

* Java 环境变量的配置问题
  常用的环境变量： ~JAVA_HOME~, ~CLASSPATH~.

  另外将 ~%JAVA_HOME%/bin~ 加入 ~PATH~ 方便命令行的使用。

  ~CLASSPATH~ 默认为 *当前目录*, 指定规则为：
  1. 对于包含类文件的 JAR 或 zip 文件，以 zip 或 JAR 文件的名称结尾
  2. 对于未命名包中的类文件，以包含类文件的目录结束
  3. 对于包中的类文件，以包含包目录的目录结束

  + [[https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html][Setting the Class Path]]

* Java 资源问题
  + [[https://docs.oracle.com/javase/8/docs/technotes/guides/lang/resources.html][Location-Independent Access to Resources]]
  + [[https://www.cnblogs.com/yejg1212/p/3270152.html][关于 Class.getResource 和 ClassLoader.getResource 的路径问题]]
    
  #+BEGIN_SRC java
    Class.getResource("name");   // current_class_file_path/name
    Class.getResource("/name");  // current_classpath/name
  #+END_SRC

  #+BEGIN_EXAMPLE
    + path
      + resource
      + -- Test.class  -- current classpath -- path

    + path
      + resource
      + -- com
           + -- rgbit
                + -- Test.class  -- current classpath -- path

    + path
      + -- com.rgbit.jar  -- current classpath -- path/com.rgbit.jar

    + com.rgbit.jar
      + -- resource
      + -- ...
  #+END_EXAMPLE

  将 ~Resources~ 目录放在顶级包或类的同级目录的原因：该位置就在 ~CLASSPATH~ 下，方便资源的寻找

* 内部类引用外部类的实例
  #+BEGIN_SRC java
    OuterClassName.this;
  #+END_SRC

* Java 编程中 Bean 类的含义
  + [[https://dzone.com/articles/the-bean-class-for-java-programming][The Bean Class for Java Programming]]
    
  Bean 类： 用于聚合或收集原始数据类型的类以及用于在程序中建模数据的类

  多数程序需要定义多个元素或值来描述它们与之交互的数据。这些元素不是单独列出每个元素，
  而是组合在一起成为一个类。

  一些强制性的规则：
  + 所有字段只能是私有的
  + 必须有默认构造函数
  + 读取或写入实例变量的方法必须以前缀 set 或 get 开头
  + bean 类应该实现可序列化的 interfaceOptional

 一些可选的规则：
 + bean 类应该有一个 toString 方法
 + bean 类应该有一个 hashCode 和一个 equals 方法
 + bean 类应该实现 Comparable 接口并具有 compareTo 方法

* null 重载的问题
  #+BEGIN_SRC java
    public class Example {
      public void method(String string) {
        // ....
      }

      public void method(Object object) {
        // ...
      }
    }
  #+END_SRC

  对于上面的代码，如果像这样调用会出现错误：
  #+BEGIN_SRC java
    Example.method(null);
  #+END_SRC

  null 对于两个重载都合适，产生了冲突，解决方案是将 null 赋值给一个引用：
  #+BEGIN_SRC java
    String string = null;
    Example.method(string);
  #+END_SRC

* Void 和 void 的使用
  void 关键字表示无返回值，而 Void 表示需要返回 null, 也只能返回 null.

  在 Lambda 表达式中，不需要返回值时可以用 ~Consumer<T>~, 对于 ~Function<T, Void>~ 来说，
  还是必须要返回 ~null~ 才行。

* 怎样实现静态方法的链式调用
  让静态方法返回指定类型的 null 值就可以了，因为静态方法的调用不依赖于实例：
  #+BEGIN_SRC java
    public class Test {
      public static Test methodA(){
        return null;
      }

      public static Test methodB(){
        return null;
      }
    }

    Test.methodA().methodB();
  #+END_SRC

* parseXXX 和 valueOf 的区别
  Java Primitive Types 的包装类都存在 parseXXX 和 valueOf 这两个方法，它们的作用很相似，
  但也存在区别：
  + parseXXX 返回的是 Primitive Types 类型的值，比如 parseInt 返回 int
  + valueOf 返回的是包装类型的值，比如 Integer.valueOf 返回 Integer

* 带标签的 break 与 continue 的使用
  Java 允许在 break 和 continue 关键字后跟一个 label 进行跳转，然而实际使用这一特性的地方很少，
  如果存在需要使用的地方，可以参考如下链接考虑修改：

  + [[https://stackoverflow.com/questions/14960419/is-using-a-labeled-break-a-good-practice-in-java][Is using a labeled break a good practice in Java? - Stack Overflow]]

* 同名标识符的优先级
  当字段名、类名、方法名、函数参数名、局部变量名存在相同名称时的优先级是怎样的？

  对于这一点，简单的规则是越靠近内部作用域的标识符优先级越高，可以参考：
  + [[https://stackoverflow.com/questions/9960560/java-instance-variable-and-method-having-same-name][java instance variable and method having same name - Stack Overflow]]

  思考：同名标识符的区分是在语义分析阶段完成的吗？

* 数组长度允许为 0 的好处
  数组长度允许为 0 的一个直接好处就是可以避免 null 值：
  #+BEGIN_SRC java
    for(int k = 0; k < strings.length; k++){
      // something
    }
  #+END_SRC

  参考：[[https://stackoverflow.com/questions/4612471/why-does-java-allow-arrays-of-size-0][Why does Java allow arrays of size 0? - Stack Overflow]]

